modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Bin"
description='''
CNPCPlus - A patch/optimization mod for CustomNPCs (Unofficial).
by Bin
'''

[[mixins]]
config="cnpcplus.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="customnpcs"
    type="required"
    versionRange="[1.21.1,)"
    ordering="AFTER"
    side="BOTH"
